spring:
  application:
    name: calendar



  # DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/h_calendar
    driver-class-name: org.h2.Driver
    username: sa
    password:



  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: update